### ISSUE TITLE
poznámky zo stretnutia so zadávateľom

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2022-FMFI/form-versions#1]
zapísať a poslať im na kontrolu a prípadné doplnenie

**Comment by gingerbraden** [comment]
<img width="361" alt="image" src="https://user-images.githubusercontent.com/99813901/194847240-2cf1c933-f3f3-442c-a5ba-fb0dd711a298.png">

Zadávateľ schválil poznámky a implementáciu
