### ISSUE TITLE
UML Class diagram

### ISSUE THREAD

**Issue by gingerbraden** [TIS2022-FMFI/form-versions#19]

**Comment by PetoVerci** [comment]
![Image](https://user-images.githubusercontent.com/99815989/200126783-2b1d8c20-d949-4f1c-b4c9-e0730bc3a46d.png)

**Comment by gingerbraden** [comment]
https://drive.google.com/file/d/1PQwTXeaAmPhDUCcHpxkQ-YM5OKG2wvvg/view?usp=share_link
