### ISSUE TITLE
UML Sequence diagram

### ISSUE THREAD

**Issue by gingerbraden** [TIS2022-FMFI/form-versions#20]

**Comment by gingerbraden** [comment]
first version created

![Image](https://user-images.githubusercontent.com/99813901/199963812-5d8c8bd3-f719-4027-97e4-998c9f2c4ae3.png)

**Comment by kostrian1** [comment]
![Image](https://user-images.githubusercontent.com/100238456/203308063-9e4efc6e-cde8-487f-ae88-ee1d154cc87f.png)
