### ISSUE TITLE
Analyzovanie SW Catia

### ISSUE THREAD

**Issue by gingerbraden** [TIS2022-FMFI/form-versions#4]
Práca so SW Catia, skúmanie sposobu formatovania suborov exportovanych z Catie

**Comment by pavelpetrovic** [comment]
verzia?
do coho sa da exportovat?
da sa citat aj povodny subor?

Main Catia V5 file extensions are:

    CATPart (part)
    CATProduct (Assembly)
    CATDrawing (drawing)
    cgr (faceted representation)
    3dxml (Lightened representation)

https://stackoverflow.com/questions/7045264/how-do-i-read-a-jpg-or-png-from-the-windows-clipboard-in-python-and-vice-versa
