### ISSUE TITLE
Schvalenie katalogu poziadaviek

### ISSUE THREAD

**Issue by gingerbraden** [TIS2022-FMFI/form-versions#9]

**Comment by gingerbraden** [comment]
@pavelpetrovic requesting review and approval

**Comment by pavelpetrovic** [comment]
3.5 ako sa k tomu pouzivatel dostane, co vsetko uvidi?
3.4. neviem skompilovat
3.7. prosim upresnit ze/ci vsetky polia zaznamov sa daju menit
ostava doriesit obrazky, prosim zavedte o tom informaciu v KP
3.6.1 prosim vysvetlit co je to za excel subor a aj do 2. casti pridat vety vysvetlujuce proces vytvarania sablony
3.6.2. uviest zoznam vsetkych typov udajov, ktore sa daju priradovat polickam
mozete pridat jednu poziadavku o spolocnej

**Comment by gingerbraden** [comment]
katalog bol schvaleny skolitelom aj zadavatelom
